[package]
name = "my_git"
version = "0.1.0"
authors = ["Florian Amsallem <florian.amsallem@epita.fr>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", features = ["yaml", "suggestions", "color"] }
sha1 = "0.6.0"
chrono = "0.4"
